language: python

python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4

install: pip install nosetests django_nose

#script: python setup.py test
script: nosetests

notifications:
  irc:
    channels: "irc.freenode.org#ahref"
    on_success: change
    on_failure: change
